# Secrets file for Streamlit deployment
# This file is used for local development and deployment configuration
# The actual GOOGLE_API_KEY will be added through the Streamlit Cloud dashboard

[default]
# Add your secrets here when deploying to Streamlit Cloud
# GOOGLE_API_KEY = "your_key_here"
